In [2]:
import pandas as pd
import numpy as np
df_main = pd.read_csv('/home/aidleroinc/Downloads/MLData.csv')

In [3]:
df = df_main.copy()

In [4]:
df

,Index,Umri,Jinsia,Mahali unapoishi,Nauli unayotumia kufika chuo,Umbali wa sehemu unapo kaa mpaka chuo,Kiasi au kipato unacho pewa kwa semester,Submitter,Submission Date,Submission ID
0,1,21.0,Male,Kijitonyama,1.0,1.0,250000.0,NaN,"8/11/2021, 3:04:03 AM",7fc8af4e
1,2,23.0,Male,Sinza,800.0,2.0,1000000.0,NaN,"8/11/2021, 3:04:41 AM",b06a608f
2,3,23.0,Male,Lugungira,800.0,8.0,10020000.0,NaN,"8/11/2021, 3:08:15 AM",47d8c775
3,4,NaN,NaN,NaN,NaN,3.6,NaN,NaN,"8/11/2021, 3:12:19 AM",db712bb8
4,5,20.0,Male,udsm,NaN,NaN,300000.0,NaN,"8/11/2021, 3:19:01 AM",cfba09f2
5,6,20.0,Male,Tegeta,500.0,12.0,300000.0,NaN,"8/11/2021, 3:22:50 AM",a5f13aeb
6,7,21.0,Male,Makumbusho,NaN,2.5,200000.0,NaN,"8/11/2021, 3:23:25 AM",e21fa200
7,8,21.0,Male,Dar,400.0,NaN,NaN,NaN,"8/11/2021, 3:27:00 AM",bff84e27
8,9,24.0,Male,Manyara,400.0,2.0,2000000.0,NaN,"8/11/2021, 3:39:35 AM",c9bf0f3a
9,10,20.0,Male,Tegeta,400.0,7.0,500000.0,NaN,"8/11/2021, 3:50:38 AM",27ecc6e5
10,11,21.0,Male,Mabibo hostel,400.0,1.5,1000000.0,NaN,"8/11/2021, 3:57:48 AM",f9c512da
11,12,21.0,Male,Golani,1000.0,3.4,NaN,NaN,"8/11/2021, 4:04:17 AM",1d28f632
12,13,21.0,Female,Sinza,400.0,3.2,1.0,NaN,"8/11/2021, 4:10:26 AM",c7a33492
13,14,23.0,Female,Dar es salaam,400.0,5.0,1000000.0,NaN,"8/11/2021, 4:12:10 AM",7f89e46f
14,15,22.0,Female,Dar -es-Salaam,400.0,8.0,500000.0,NaN,"8/11/2021, 4:16:50 AM",be3ab227
15,16,21.0,Male,Magomeni,400.0,3.0,500000.0,NaN,"8/11/2021, 4:17:03 AM",f79d5178
16,17,40.0,Male,coict hostel,NaN,NaN,1000000.0,NaN,"8/11/2021, 4:18:31 AM",646654f
17,18,21.0,Male,Tabata,1000.0,5.0,400000.0,NaN,"8/11/2021, 4:23:35 AM",3cbd4ce7
18,19,21.0,Male,Tabata,1000.0,12.0,10000000.0,NaN,"8/11/2021, 4:26:00 AM",51555e31
19,20,35.0,Male,Dsm,400.0,5.0,2500000.0,NaN,"8/11/2021, 4:30:09 AM",d80af7dc
20,21,91.0,Female,Wakanda,100000.0,500000.0,140000000.0,NaN,"8/11/2021, 4:31:41 AM",db8a6da8
21,22,22.0,Female,Makumbusho,400.0,NaN,1000000.0,NaN,"8/11/2021, 4:31:54 AM",ce7b8c72
22,23,21.0,Male,Tanesco,400.0,3.0,500000.0,NaN,"8/11/2021, 4:34:57 AM",ffc99a73
23,24,20.0,Female,Kibaha,2000.0,NaN,400000.0,NaN,"8/11/2021, 4:35:58 AM",5ed7e554
24,25,20.0,Female,MbeziBeach africana,2000.0,NaN,NaN,NaN,"8/11/2021, 4:36:13 AM",c904b2e4
25,26,20.0,Male,Survey,1000.0,NaN,NaN,NaN,"8/11/2021, 4:37:48 AM",7f90ed0f
26,27,22.0,Male,Tandale,800.0,7.2,520000.0,NaN,"8/11/2021, 4:39:19 AM",1df59cc3
27,28,23.0,Female,Tegeta,2000.0,10.0,50000.0,NaN,"8/11/2021, 4:42:48 AM",28bfbd2a
28,29,24.0,Male,Golani,1000.0,2.0,200000.0,NaN,"8/11/2021, 4:44:32 AM",481b148e
29,30,21.0,Female,Changanyikeni mbuyuni,500.0,NaN,150000.0,NaN,"8/11/2021, 4:46:56 AM",f5862bbf
30,31,19.0,Male,Kijitonyama,NaN,1.0,200000.0,NaN,"8/11/2021, 4:58:02 AM",8cd2b827
31,32,19.0,Female,mabibo,400.0,2.0,400000.0,NaN,"8/11/2021, 5:06:22 AM",bd13af88
32,33,22.0,Female,Mikocheni B,2800.0,2.0,1000000.0,NaN,"8/11/2021, 5:09:30 AM",7b779de
33,34,22.0,Female,Kimara,500.0,20.0,1000000.0,NaN,"8/11/2021, 5:11:00 AM",22ba2f89
34,35,21.0,Female,Goba,1000.0,10.0,850000.0,NaN,"8/11/2021, 5:15:56 AM",e835acd5
35,36,22.0,Female,Kimara,1000.0,10.0,500000.0,NaN,"8/11/2021, 5:22:19 AM",b5b05b91
36,37,21.0,Female,coict hostel,950.0,2.0,500000.0,NaN,"8/11/2021, 5:22:28 AM",139bc678
37,38,24.0,Male,Makumbusho,NaN,0.5,1000000.0,NaN,"8/11/2021, 5:23:35 AM",e5bce7c5
38,39,21.0,Male,kijitonyama,400.0,2.0,700000.0,NaN,"8/11/2021, 5:23:44 AM",957f9111
39,40,NaN,NaN,NaN,NaN,NaN,1000.0,NaN,"8/11/2021, 5:26:54 AM",8a6470e5
40,41,22.0,Male,Tabatq,400.0,15.0,900000.0,NaN,"8/11/2021, 5:28:01 AM",fa2736ab
41,42,22.0,Male,ubungo,500.0,8.0,500000.0,NaN,"8/11/2021, 5:28:15 AM",3514aeda
42,43,23.0,Male,riverside,500.0,10.0,600000.0,NaN,"8/11/2021, 5:29:21 AM",4c79ecbc
43,44,24.0,Female,Kijitonyama,NaN,2.5,1000000.0,NaN,"8/11/2021, 5:29:37 AM",5c1df9a3
44,45,21.0,Female,Kijitonyama,1500.0,1.5,500000.0,NaN,"8/11/2021, 5:32:43 AM",d63434cb
45,46,23.0,Male,Mwenge - Mpakani,400.0,5.0,1024000.0,NaN,"8/11/2021, 5:33:04 AM",c923f38f
46,47,24.0,Male,Buza,1000.0,19.0,700000.0,NaN,"8/11/2021, 5:38:35 AM",4d97bc42
47,48,24.0,Male,magufuli hostel,NaN,NaN,200000.0,NaN,"8/11/2021, 5:41:25 AM",f5e93d66
48,49,19.0,Female,tabata,2500.0,17.0,480000.0,peter wilfred,"8/11/2021, 5:42:05 AM",1f762ebd
49,50,20.0,Male,udsm,NaN,NaN,300000.0,peter wilfred,"8/11/2021, 5:45:09 AM",e176252d

In [5]:
del df['Submitter']
del df['Submission Date']
del df['Submission ID']

In [6]:
df

,Index,Umri,Jinsia,Mahali unapoishi,Nauli unayotumia kufika chuo,Umbali wa sehemu unapo kaa mpaka chuo,Kiasi au kipato unacho pewa kwa semester
0,1,21.0,Male,Kijitonyama,1.0,1.0,250000.0
1,2,23.0,Male,Sinza,800.0,2.0,1000000.0
2,3,23.0,Male,Lugungira,800.0,8.0,10020000.0
3,4,NaN,NaN,NaN,NaN,3.6,NaN
4,5,20.0,Male,udsm,NaN,NaN,300000.0
5,6,20.0,Male,Tegeta,500.0,12.0,300000.0
6,7,21.0,Male,Makumbusho,NaN,2.5,200000.0
7,8,21.0,Male,Dar,400.0,NaN,NaN
8,9,24.0,Male,Manyara,400.0,2.0,2000000.0
9,10,20.0,Male,Tegeta,400.0,7.0,500000.0
10,11,21.0,Male,Mabibo hostel,400.0,1.5,1000000.0
11,12,21.0,Male,Golani,1000.0,3.4,NaN
12,13,21.0,Female,Sinza,400.0,3.2,1.0
13,14,23.0,Female,Dar es salaam,400.0,5.0,1000000.0
14,15,22.0,Female,Dar -es-Salaam,400.0,8.0,500000.0
15,16,21.0,Male,Magomeni,400.0,3.0,500000.0
16,17,40.0,Male,coict hostel,NaN,NaN,1000000.0
17,18,21.0,Male,Tabata,1000.0,5.0,400000.0
18,19,21.0,Male,Tabata,1000.0,12.0,10000000.0
19,20,35.0,Male,Dsm,400.0,5.0,2500000.0
20,21,91.0,Female,Wakanda,100000.0,500000.0,140000000.0
21,22,22.0,Female,Makumbusho,400.0,NaN,1000000.0
22,23,21.0,Male,Tanesco,400.0,3.0,500000.0
23,24,20.0,Female,Kibaha,2000.0,NaN,400000.0
24,25,20.0,Female,MbeziBeach africana,2000.0,NaN,NaN
25,26,20.0,Male,Survey,1000.0,NaN,NaN
26,27,22.0,Male,Tandale,800.0,7.2,520000.0
27,28,23.0,Female,Tegeta,2000.0,10.0,50000.0
28,29,24.0,Male,Golani,1000.0,2.0,200000.0
29,30,21.0,Female,Changanyikeni mbuyuni,500.0,NaN,150000.0
30,31,19.0,Male,Kijitonyama,NaN,1.0,200000.0
31,32,19.0,Female,mabibo,400.0,2.0,400000.0
32,33,22.0,Female,Mikocheni B,2800.0,2.0,1000000.0
33,34,22.0,Female,Kimara,500.0,20.0,1000000.0
34,35,21.0,Female,Goba,1000.0,10.0,850000.0
35,36,22.0,Female,Kimara,1000.0,10.0,500000.0
36,37,21.0,Female,coict hostel,950.0,2.0,500000.0
37,38,24.0,Male,Makumbusho,NaN,0.5,1000000.0
38,39,21.0,Male,kijitonyama,400.0,2.0,700000.0
39,40,NaN,NaN,NaN,NaN,NaN,1000.0
40,41,22.0,Male,Tabatq,400.0,15.0,900000.0
41,42,22.0,Male,ubungo,500.0,8.0,500000.0
42,43,23.0,Male,riverside,500.0,10.0,600000.0
43,44,24.0,Female,Kijitonyama,NaN,2.5,1000000.0
44,45,21.0,Female,Kijitonyama,1500.0,1.5,500000.0
45,46,23.0,Male,Mwenge - Mpakani,400.0,5.0,1024000.0
46,47,24.0,Male,Buza,1000.0,19.0,700000.0
47,48,24.0,Male,magufuli hostel,NaN,NaN,200000.0
48,49,19.0,Female,tabata,2500.0,17.0,480000.0
49,50,20.0,Male,udsm,NaN,NaN,300000.0

In [7]:
df.columns = ['index','age','gender','location','tfee','distance','stipend']

In [8]:

df

,index,age,gender,location,tfee,distance,stipend
0,1,21.0,Male,Kijitonyama,1.0,1.0,250000.0
1,2,23.0,Male,Sinza,800.0,2.0,1000000.0
2,3,23.0,Male,Lugungira,800.0,8.0,10020000.0
3,4,NaN,NaN,NaN,NaN,3.6,NaN
4,5,20.0,Male,udsm,NaN,NaN,300000.0
5,6,20.0,Male,Tegeta,500.0,12.0,300000.0
6,7,21.0,Male,Makumbusho,NaN,2.5,200000.0
7,8,21.0,Male,Dar,400.0,NaN,NaN
8,9,24.0,Male,Manyara,400.0,2.0,2000000.0
9,10,20.0,Male,Tegeta,400.0,7.0,500000.0
10,11,21.0,Male,Mabibo hostel,400.0,1.5,1000000.0
11,12,21.0,Male,Golani,1000.0,3.4,NaN
12,13,21.0,Female,Sinza,400.0,3.2,1.0
13,14,23.0,Female,Dar es salaam,400.0,5.0,1000000.0
14,15,22.0,Female,Dar -es-Salaam,400.0,8.0,500000.0
15,16,21.0,Male,Magomeni,400.0,3.0,500000.0
16,17,40.0,Male,coict hostel,NaN,NaN,1000000.0
17,18,21.0,Male,Tabata,1000.0,5.0,400000.0
18,19,21.0,Male,Tabata,1000.0,12.0,10000000.0
19,20,35.0,Male,Dsm,400.0,5.0,2500000.0
20,21,91.0,Female,Wakanda,100000.0,500000.0,140000000.0
21,22,22.0,Female,Makumbusho,400.0,NaN,1000000.0
22,23,21.0,Male,Tanesco,400.0,3.0,500000.0
23,24,20.0,Female,Kibaha,2000.0,NaN,400000.0
24,25,20.0,Female,MbeziBeach africana,2000.0,NaN,NaN
25,26,20.0,Male,Survey,1000.0,NaN,NaN
26,27,22.0,Male,Tandale,800.0,7.2,520000.0
27,28,23.0,Female,Tegeta,2000.0,10.0,50000.0
28,29,24.0,Male,Golani,1000.0,2.0,200000.0
29,30,21.0,Female,Changanyikeni mbuyuni,500.0,NaN,150000.0
30,31,19.0,Male,Kijitonyama,NaN,1.0,200000.0
31,32,19.0,Female,mabibo,400.0,2.0,400000.0
32,33,22.0,Female,Mikocheni B,2800.0,2.0,1000000.0
33,34,22.0,Female,Kimara,500.0,20.0,1000000.0
34,35,21.0,Female,Goba,1000.0,10.0,850000.0
35,36,22.0,Female,Kimara,1000.0,10.0,500000.0
36,37,21.0,Female,coict hostel,950.0,2.0,500000.0
37,38,24.0,Male,Makumbusho,NaN,0.5,1000000.0
38,39,21.0,Male,kijitonyama,400.0,2.0,700000.0
39,40,NaN,NaN,NaN,NaN,NaN,1000.0
40,41,22.0,Male,Tabatq,400.0,15.0,900000.0
41,42,22.0,Male,ubungo,500.0,8.0,500000.0
42,43,23.0,Male,riverside,500.0,10.0,600000.0
43,44,24.0,Female,Kijitonyama,NaN,2.5,1000000.0
44,45,21.0,Female,Kijitonyama,1500.0,1.5,500000.0
45,46,23.0,Male,Mwenge - Mpakani,400.0,5.0,1024000.0
46,47,24.0,Male,Buza,1000.0,19.0,700000.0
47,48,24.0,Male,magufuli hostel,NaN,NaN,200000.0
48,49,19.0,Female,tabata,2500.0,17.0,480000.0
49,50,20.0,Male,udsm,NaN,NaN,300000.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     50 non-null     int64
 1   age       48 non-null     float64
 2   gender    48 non-null     object
 3   location  48 non-null     object
 4   tfee      40 non-null     float64
 5   distance  39 non-null     float64
 6   stipend   45 non-null     float64
dtypes: float64(4), int64(1), object(2)
memory usage: 2.9+ KB

In [10]:
new_df = df.dropna()

In [11]:
new_df

    index   age  gender          location      tfee  distance      stipend
0       1  21.0    Male      Kijitonyama        1.0       1.0     250000.0
1       2  23.0    Male             Sinza     800.0       2.0    1000000.0
2       3  23.0    Male         Lugungira     800.0       8.0   10020000.0
5       6  20.0    Male            Tegeta     500.0      12.0     300000.0
8       9  24.0    Male           Manyara     400.0       2.0    2000000.0
9      10  20.0    Male            Tegeta     400.0       7.0     500000.0
10     11  21.0    Male     Mabibo hostel     400.0       1.5    1000000.0
12     13  21.0  Female             Sinza     400.0       3.2          1.0
13     14  23.0  Female     Dar es salaam     400.0       5.0    1000000.0
14     15  22.0  Female    Dar -es-Salaam     400.0       8.0     500000.0
15     16  21.0    Male          Magomeni     400.0       3.0     500000.0
17     18  21.0    Male            Tabata    1000.0       5.0     400000.0
18     19  21.0    Male            Tabata    1000.0      12.0   10000000.0
19     20  35.0    Male              Dsm      400.0       5.0    2500000.0
20     21  91.0  Female           Wakanda  100000.0  500000.0  140000000.0
22     23  21.0    Male           Tanesco     400.0       3.0     500000.0
26     27  22.0    Male           Tandale     800.0       7.2     520000.0
27     28  23.0  Female            Tegeta    2000.0      10.0      50000.0
28     29  24.0    Male            Golani    1000.0       2.0     200000.0
31     32  19.0  Female            mabibo     400.0       2.0     400000.0
32     33  22.0  Female       Mikocheni B    2800.0       2.0    1000000.0
33     34  22.0  Female           Kimara      500.0      20.0    1000000.0
34     35  21.0  Female              Goba    1000.0      10.0     850000.0
35     36  22.0  Female            Kimara    1000.0      10.0     500000.0
36     37  21.0  Female      coict hostel     950.0       2.0     500000.0
38     39  21.0    Male       kijitonyama     400.0       2.0     700000.0
40     41  22.0    Male            Tabatq     400.0      15.0     900000.0
41     42  22.0    Male            ubungo     500.0       8.0     500000.0
42     43  23.0    Male         riverside     500.0      10.0     600000.0
44     45  21.0  Female       Kijitonyama    1500.0       1.5     500000.0
45     46  23.0    Male  Mwenge - Mpakani     400.0       5.0    1024000.0
46     47  24.0    Male              Buza    1000.0      19.0     700000.0
48     49  19.0  Female            tabata    2500.0      17.0     480000.0